const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_UNAUTHENTICATED = 401;
const STATES_CODE_UNAUTHORIZED = 403;
const STATUS_CODE_PAGE_NOT_FOUND = 404;
const STATUS_CODE_CONFLICT = 409;
const STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
const STATUS_CODE_SUCCESS = 200;

module.exports = {
  STATUS_CODE_BAD_REQUEST,
  STATUS_CODE_UNAUTHENTICATED,
  STATES_CODE_UNAUTHORIZED,
  STATUS_CODE_PAGE_NOT_FOUND,
  STATUS_CODE_CONFLICT,
  STATUS_CODE_INTERNAL_SERVER_ERROR,
  STATUS_CODE_SUCCESS,
};
